In [2]:
import pandas as pd

In [41]:
map_df = pd.read_csv('../crosswalk_csv/d_labitems_to_loinc.csv')
with open('missing_measurement_mappings.csv') as fin:
    missing_mci = [x.rstrip('\n') for x in fin.readlines()]
format_str = 'ALTER TABLE measurement SET measurement_concept_id = {mci} WHERE measurement_concept_id = 0 AND measurement_source_value = {msv}'

mapping_dict = {}
for code in missing_mci:
    if '|' in code:
        codes = code.split('|')
        try:
            omop_concept_id = list(map_df[map_df['itemid (omop_source_code)']==int(codes[0])].omop_concept_id)[0]
        except IndexError:
            try:
                omop_concept_id = list(map_df[map_df['itemid (omop_source_code)']==int(codes[1])].omop_concept_id)[0]
            except IndexError:
                continue
        if not pd.isna(omop_concept_id):
            mapping_dict[code] = omop_concept_id
    else:
        try:
            omop_concept_id = list(map_df[map_df['itemid (omop_source_code)']==int(code)].omop_concept_id)[0]
        except IndexError:
            continue
        if not pd.isna(omop_concept_id):
            mapping_dict[code] = omop_concept_id

In [42]:
full_sql_string = ''
for key, value in mapping_dict.items():
    filled_in_str = format_str.format(mci=value, msv=key)
    full_sql_string += f'\n{filled_in_str}'
full_sql_string

'\nALTER TABLE measurement SET measurement_concept_id = 3001260 WHERE measurement_concept_id = 0 AND measurement_source_value = 51062\nALTER TABLE measurement SET measurement_concept_id = 3033042 WHERE measurement_concept_id = 0 AND measurement_source_value = 50848\nALTER TABLE measurement SET measurement_concept_id = 3004717 WHERE measurement_concept_id = 0 AND measurement_source_value = 51922\nALTER TABLE measurement SET measurement_concept_id = 3018447 WHERE measurement_concept_id = 0 AND measurement_source_value = 51713\nALTER TABLE measurement SET measurement_concept_id = 3045028 WHERE measurement_concept_id = 0 AND measurement_source_value = 51879\nALTER TABLE measurement SET measurement_concept_id = 3018760 WHERE measurement_concept_id = 0 AND measurement_source_value = 51219\nALTER TABLE measurement SET measurement_concept_id = 3004176 WHERE measurement_concept_id = 0 AND measurement_source_value = 51980\nALTER TABLE measurement SET measurement_concept_id = 3024394 WHERE measurement_concept_id = 0 AND measurement_source_value = 52305\nALTER TABLE measurement SET measurement_concept_id = 3023116 WHERE measurement_concept_id = 0 AND measurement_source_value = 51183\nALTER TABLE measurement SET measurement_concept_id = 3006576 WHERE measurement_concept_id = 0 AND measurement_source_value = 50803\nALTER TABLE measurement SET measurement_concept_id = 40757337 WHERE measurement_concept_id = 0 AND measurement_source_value = 51598\nALTER TABLE measurement SET measurement_concept_id = 3026992 WHERE measurement_concept_id = 0 AND measurement_source_value = 51158\nALTER TABLE measurement SET measurement_concept_id = 3004437 WHERE measurement_concept_id = 0 AND measurement_source_value = 51116\nALTER TABLE measurement SET measurement_concept_id = 3023386 WHERE measurement_concept_id = 0 AND measurement_source_value = 50850\nALTER TABLE measurement SET measurement_concept_id = 3013098 WHERE measurement_concept_id = 0 AND measurement_source_value = 51057\nALTER TABLE measurement SET measurement_concept_id = 3029717 WHERE measurement_concept_id = 0 AND measurement_source_value = 51395\nALTER TABLE measurement SET measurement_concept_id = 3029714 WHERE measurement_concept_id = 0 AND measurement_source_value = 51394\nALTER TABLE measurement SET measurement_concept_id = 3037201 WHERE measurement_concept_id = 0 AND measurement_source_value = 51272\nALTER TABLE measurement SET measurement_concept_id = 3039497 WHERE measurement_concept_id = 0 AND measurement_source_value = 52312\nALTER TABLE measurement SET measurement_concept_id = 3010109 WHERE measurement_concept_id = 0 AND measurement_source_value = 51083\nALTER TABLE measurement SET measurement_concept_id = 3028079 WHERE measurement_concept_id = 0 AND measurement_source_value = 51427\nALTER TABLE measurement SET measurement_concept_id = 3025842 WHERE measurement_concept_id = 0 AND measurement_source_value = 51156\nALTER TABLE measurement SET measurement_concept_id = 40758985 WHERE measurement_concept_id = 0 AND measurement_source_value = 51336\nALTER TABLE measurement SET measurement_concept_id = 3002651 WHERE measurement_concept_id = 0 AND measurement_source_value = 50840\nALTER TABLE measurement SET measurement_concept_id = 3026595 WHERE measurement_concept_id = 0 AND measurement_source_value = 51154\nALTER TABLE measurement SET measurement_concept_id = 1616395 WHERE measurement_concept_id = 0 AND measurement_source_value = 52108\nALTER TABLE measurement SET measurement_concept_id = 3022613 WHERE measurement_concept_id = 0 AND measurement_source_value = 51220\nALTER TABLE measurement SET measurement_concept_id = 3000905 WHERE measurement_concept_id = 0 AND measurement_source_value = 51755\nALTER TABLE measurement SET measurement_concept_id = 40757492 WHERE measurement_concept_id = 0 AND measurement_source_value = 51048\nALTER TABLE measurement SET measurement_concept_id = 3020383 WHERE measurement_concept_id = 0 AND measurement_source_value = 51184\nALTER TABLE measurement SET measurement_concept_id = 3019473 WHERE measurement_concept_id = 0 AND measurement_source_value = 51802\nALTER TABLE measurement SET measurement_concept_id = 40760537 WHERE measurement_concept_id = 0 AND measurement_source_value = 51416\nALTER TABLE measurement SET measurement_concept_id = 40766151 WHERE measurement_concept_id = 0 AND measurement_source_value = 50869\nALTER TABLE measurement SET measurement_concept_id = 3022386 WHERE measurement_concept_id = 0 AND measurement_source_value = 51753\nALTER TABLE measurement SET measurement_concept_id = 3033894 WHERE measurement_concept_id = 0 AND measurement_source_value = 51404\nALTER TABLE measurement SET measurement_concept_id = 3016512 WHERE measurement_concept_id = 0 AND measurement_source_value = 52263\nALTER TABLE measurement SET measurement_concept_id = 3004131 WHERE measurement_concept_id = 0 AND measurement_source_value = 51968\nALTER TABLE measurement SET measurement_concept_id = 3027184 WHERE measurement_concept_id = 0 AND measurement_source_value = 51243\nALTER TABLE measurement SET measurement_concept_id = 3006033 WHERE measurement_concept_id = 0 AND measurement_source_value = 51617\nALTER TABLE measurement SET measurement_concept_id = 43533839 WHERE measurement_concept_id = 0 AND measurement_source_value = 52131\nALTER TABLE measurement SET measurement_concept_id = 3038184 WHERE measurement_concept_id = 0 AND measurement_source_value = 51590\nALTER TABLE measurement SET measurement_concept_id = 3020412 WHERE measurement_concept_id = 0 AND measurement_source_value = 51290\nALTER TABLE measurement SET measurement_concept_id = 3033987 WHERE measurement_concept_id = 0 AND measurement_source_value = 51688\nALTER TABLE measurement SET measurement_concept_id = 3006670 WHERE measurement_concept_id = 0 AND measurement_source_value = 51798\nALTER TABLE measurement SET measurement_concept_id = 3025698 WHERE measurement_concept_id = 0 AND measurement_source_value = 52227\nALTER TABLE measurement SET measurement_concept_id = 3019174 WHERE measurement_concept_id = 0 AND measurement_source_value = 52109\nALTER TABLE measurement SET measurement_concept_id = 3041079 WHERE measurement_concept_id = 0 AND measurement_source_value = 52391\nALTER TABLE measurement SET measurement_concept_id = 40758359 WHERE measurement_concept_id = 0 AND measurement_source_value = 51338\nALTER TABLE measurement SET measurement_concept_id = 3016937 WHERE measurement_concept_id = 0 AND measurement_source_value = 50846\nALTER TABLE measurement SET measurement_concept_id = 3026681 WHERE measurement_concept_id = 0 AND measurement_source_value = 51058\nALTER TABLE measurement SET measurement_concept_id = 3038288 WHERE measurement_concept_id = 0 AND measurement_source_value = 51872\nALTER TABLE measurement SET measurement_concept_id = 3035460 WHERE measurement_concept_id = 0 AND measurement_source_value = 51264\nALTER TABLE measurement SET measurement_concept_id = 3029960 WHERE measurement_concept_id = 0 AND measurement_source_value = 51307\nALTER TABLE measurement SET measurement_concept_id = 3022547 WHERE measurement_concept_id = 0 AND measurement_source_value = 51985\nALTER TABLE measurement SET measurement_concept_id = 3011681 WHERE measurement_concept_id = 0 AND measurement_source_value = 51435\nALTER TABLE measurement SET measurement_concept_id = 3000822 WHERE measurement_concept_id = 0 AND measurement_source_value = 51029\nALTER TABLE measurement SET measurement_concept_id = 3000963 WHERE measurement_concept_id = 0 AND measurement_source_value = 50855\nALTER TABLE measurement SET measurement_concept_id = 3026757 WHERE measurement_concept_id = 0 AND measurement_source_value = 52093\nALTER TABLE measurement SET measurement_concept_id = 3007950 WHERE measurement_concept_id = 0 AND measurement_source_value = 52002\nALTER TABLE measurement SET measurement_concept_id = 3011846 WHERE measurement_concept_id = 0 AND measurement_source_value = 51065\nALTER TABLE measurement SET measurement_concept_id = 40758914 WHERE measurement_concept_id = 0 AND measurement_source_value = 52369\nALTER TABLE measurement SET measurement_concept_id = 3018543 WHERE measurement_concept_id = 0 AND measurement_source_value = 52992\nALTER TABLE measurement SET measurement_concept_id = 3025285 WHERE measurement_concept_id = 0 AND measurement_source_value = 50921\nALTER TABLE measurement SET measurement_concept_id = 3046019 WHERE measurement_concept_id = 0 AND measurement_source_value = 52331\nALTER TABLE measurement SET measurement_concept_id = 3036353 WHERE measurement_concept_id = 0 AND measurement_source_value = 51429\nALTER TABLE measurement SET measurement_concept_id = 3036243 WHERE measurement_concept_id = 0 AND measurement_source_value = 51041\nALTER TABLE measurement SET measurement_concept_id = 3016662 WHERE measurement_concept_id = 0 AND measurement_source_value = 51032\nALTER TABLE measurement SET measurement_concept_id = 3007930 WHERE measurement_concept_id = 0 AND measurement_source_value = 50814\nALTER TABLE measurement SET measurement_concept_id = 40761803 WHERE measurement_concept_id = 0 AND measurement_source_value = 50870\nALTER TABLE measurement SET measurement_concept_id = 3021562 WHERE measurement_concept_id = 0 AND measurement_source_value = 51167\nALTER TABLE measurement SET measurement_concept_id = 3016251 WHERE measurement_concept_id = 0 AND measurement_source_value = 51460\nALTER TABLE measurement SET measurement_concept_id = 3010156 WHERE measurement_concept_id = 0 AND measurement_source_value = 51652\nALTER TABLE measurement SET measurement_concept_id = 3002022 WHERE measurement_concept_id = 0 AND measurement_source_value = 51270\nALTER TABLE measurement SET measurement_concept_id = 3050479 WHERE measurement_concept_id = 0 AND measurement_source_value = 52135\nALTER TABLE measurement SET measurement_concept_id = 3036603 WHERE measurement_concept_id = 0 AND measurement_source_value = 51109\nALTER TABLE measurement SET measurement_concept_id = 3006957 WHERE measurement_concept_id = 0 AND measurement_source_value = 51742\nALTER TABLE measurement SET measurement_concept_id = 3046317 WHERE measurement_concept_id = 0 AND measurement_source_value = 51365\nALTER TABLE measurement SET measurement_concept_id = 3013339 WHERE measurement_concept_id = 0 AND measurement_source_value = 51725\nALTER TABLE measurement SET measurement_concept_id = 3009041 WHERE measurement_concept_id = 0 AND measurement_source_value = 51138\nALTER TABLE measurement SET measurement_concept_id = 3047187 WHERE measurement_concept_id = 0 AND measurement_source_value = 51230\nALTER TABLE measurement SET measurement_concept_id = 3005131 WHERE measurement_concept_id = 0 AND measurement_source_value = 51613\nALTER TABLE measurement SET measurement_concept_id = 3026532 WHERE measurement_concept_id = 0 AND measurement_source_value = 51791\nALTER TABLE measurement SET measurement_concept_id = 3020475 WHERE measurement_concept_id = 0 AND measurement_source_value = 51621\nALTER TABLE measurement SET measurement_concept_id = 3013650 WHERE measurement_concept_id = 0 AND measurement_source_value = 51697\nALTER TABLE measurement SET measurement_concept_id = 3008838 WHERE measurement_concept_id = 0 AND measurement_source_value = 51125\nALTER TABLE measurement SET measurement_concept_id = 3018954 WHERE measurement_concept_id = 0 AND measurement_source_value = 52720\nALTER TABLE measurement SET measurement_concept_id = 3015813 WHERE measurement_concept_id = 0 AND measurement_source_value = 51139\nALTER TABLE measurement SET measurement_concept_id = 3023316 WHERE measurement_concept_id = 0 AND measurement_source_value = 52311\nALTER TABLE measurement SET measurement_concept_id = 3017675 WHERE measurement_concept_id = 0 AND measurement_source_value = 51653\nALTER TABLE measurement SET measurement_concept_id = 3033486 WHERE measurement_concept_id = 0 AND measurement_source_value = 51511\nALTER TABLE measurement SET measurement_concept_id = 3014576 WHERE measurement_concept_id = 0 AND measurement_source_value = 52535\nALTER TABLE measurement SET measurement_concept_id = 37019529 WHERE measurement_concept_id = 0 AND measurement_source_value = 51150\nALTER TABLE measurement SET measurement_concept_id = 3011004 WHERE measurement_concept_id = 0 AND measurement_source_value = 50838\nALTER TABLE measurement SET measurement_concept_id = 3021849 WHERE measurement_concept_id = 0 AND measurement_source_value = 51614\nALTER TABLE measurement SET measurement_concept_id = 40757477 WHERE measurement_concept_id = 0 AND measurement_source_value = 51927\nALTER TABLE measurement SET measurement_concept_id = 3002253 WHERE measurement_concept_id = 0 AND measurement_source_value = 51996\nALTER TABLE measurement SET measurement_concept_id = 3002523 WHERE measurement_concept_id = 0 AND measurement_source_value = 51870\nALTER TABLE measurement SET measurement_concept_id = 3015182 WHERE measurement_concept_id = 0 AND measurement_source_value = 52172\nALTER TABLE measurement SET measurement_concept_id = 3003356 WHERE measurement_concept_id = 0 AND measurement_source_value = 51500\nALTER TABLE measurement SET measurement_concept_id = 3004400 WHERE measurement_concept_id = 0 AND measurement_source_value = 51309\nALTER TABLE measurement SET measurement_concept_id = 3003329 WHERE measurement_concept_id = 0 AND measurement_source_value = 51375\nALTER TABLE measurement SET measurement_concept_id = 3050238 WHERE measurement_concept_id = 0 AND measurement_source_value = 51372\nALTER TABLE measurement SET measurement_concept_id = 3048505 WHERE measurement_concept_id = 0 AND measurement_source_value = 51648\nALTER TABLE measurement SET measurement_concept_id = 3014637 WHERE measurement_concept_id = 0 AND measurement_source_value = 51061\nALTER TABLE measurement SET measurement_concept_id = 3043694 WHERE measurement_concept_id = 0 AND measurement_source_value = 51377\nALTER TABLE measurement SET measurement_concept_id = 3035196 WHERE measurement_concept_id = 0 AND measurement_source_value = 52358\nALTER TABLE measurement SET measurement_concept_id = 3008266 WHERE measurement_concept_id = 0 AND measurement_source_value = 52221\nALTER TABLE measurement SET measurement_concept_id = 3024655 WHERE measurement_concept_id = 0 AND measurement_source_value = 51027\nALTER TABLE measurement SET measurement_concept_id = 3025065 WHERE measurement_concept_id = 0 AND measurement_source_value = 51052\nALTER TABLE measurement SET measurement_concept_id = 3016920 WHERE measurement_concept_id = 0 AND measurement_source_value = 51795\nALTER TABLE measurement SET measurement_concept_id = 3024449 WHERE measurement_concept_id = 0 AND measurement_source_value = 51655\nALTER TABLE measurement SET measurement_concept_id = 3005532 WHERE measurement_concept_id = 0 AND measurement_source_value = 51446\nALTER TABLE measurement SET measurement_concept_id = 3000551 WHERE measurement_concept_id = 0 AND measurement_source_value = 50896\nALTER TABLE measurement SET measurement_concept_id = 21492989 WHERE measurement_concept_id = 0 AND measurement_source_value = 51875\nALTER TABLE measurement SET measurement_concept_id = 3034891 WHERE measurement_concept_id = 0 AND measurement_source_value = 52301\nALTER TABLE measurement SET measurement_concept_id = 40761570 WHERE measurement_concept_id = 0 AND measurement_source_value = 52286\nALTER TABLE measurement SET measurement_concept_id = 3021322 WHERE measurement_concept_id = 0 AND measurement_source_value = 50913\nALTER TABLE measurement SET measurement_concept_id = 3043156 WHERE measurement_concept_id = 0 AND measurement_source_value = 50839\nALTER TABLE measurement SET measurement_concept_id = 3033533 WHERE measurement_concept_id = 0 AND measurement_source_value = 51692\nALTER TABLE measurement SET measurement_concept_id = 3034860 WHERE measurement_concept_id = 0 AND measurement_source_value = 51625\nALTER TABLE measurement SET measurement_concept_id = 3047169 WHERE measurement_concept_id = 0 AND measurement_source_value = 51627\nALTER TABLE measurement SET measurement_concept_id = 40760535 WHERE measurement_concept_id = 0 AND measurement_source_value = 51412\nALTER TABLE measurement SET measurement_concept_id = 3020358 WHERE measurement_concept_id = 0 AND measurement_source_value = 52087\nALTER TABLE measurement SET measurement_concept_id = 3010251 WHERE measurement_concept_id = 0 AND measurement_source_value = 50832\nALTER TABLE measurement SET measurement_concept_id = 3028193 WHERE measurement_concept_id = 0 AND measurement_source_value = 51028\nALTER TABLE measurement SET measurement_concept_id = 3029723 WHERE measurement_concept_id = 0 AND measurement_source_value = 51320\nALTER TABLE measurement SET measurement_concept_id = 3034639 WHERE measurement_concept_id = 0 AND measurement_source_value = 50854\nALTER TABLE measurement SET measurement_concept_id = 3021119 WHERE measurement_concept_id = 0 AND measurement_source_value = 51624\nALTER TABLE measurement SET measurement_concept_id = 3013520 WHERE measurement_concept_id = 0 AND measurement_source_value = 50898\nALTER TABLE measurement SET measurement_concept_id = 21493682 WHERE measurement_concept_id = 0 AND measurement_source_value = 52184\nALTER TABLE measurement SET measurement_concept_id = 3018064 WHERE measurement_concept_id = 0 AND measurement_source_value = 51319\nALTER TABLE measurement SET measurement_concept_id = 3006866 WHERE measurement_concept_id = 0 AND measurement_source_value = 50851\nALTER TABLE measurement SET measurement_concept_id = 3032694 WHERE measurement_concept_id = 0 AND measurement_source_value = 51317\nALTER TABLE measurement SET measurement_concept_id = 3044938 WHERE measurement_concept_id = 0 AND measurement_source_value = 51865\nALTER TABLE measurement SET measurement_concept_id = 3039528 WHERE measurement_concept_id = 0 AND measurement_source_value = 51447\nALTER TABLE measurement SET measurement_concept_id = 3005770 WHERE measurement_concept_id = 0 AND measurement_source_value = 51080\nALTER TABLE measurement SET measurement_concept_id = 3035081 WHERE measurement_concept_id = 0 AND measurement_source_value = 51313\nALTER TABLE measurement SET measurement_concept_id = 3005029 WHERE measurement_concept_id = 0 AND measurement_source_value = 51043\nALTER TABLE measurement SET measurement_concept_id = 3004327 WHERE measurement_concept_id = 0 AND measurement_source_value = 52769\nALTER TABLE measurement SET measurement_concept_id = 3045452 WHERE measurement_concept_id = 0 AND measurement_source_value = 51229\nALTER TABLE measurement SET measurement_concept_id = 3044883 WHERE measurement_concept_id = 0 AND measurement_source_value = 51689\nALTER TABLE measurement SET measurement_concept_id = 3022575 WHERE measurement_concept_id = 0 AND measurement_source_value = 51754\nALTER TABLE measurement SET measurement_concept_id = 40763311 WHERE measurement_concept_id = 0 AND measurement_source_value = 51986\nALTER TABLE measurement SET measurement_concept_id = 3023103 WHERE measurement_concept_id = 0 AND measurement_source_value = 52610\nALTER TABLE measurement SET measurement_concept_id = 3016750 WHERE measurement_concept_id = 0 AND measurement_source_value = 51101\nALTER TABLE measurement SET measurement_concept_id = 3004501 WHERE measurement_concept_id = 0 AND measurement_source_value = 52569\nALTER TABLE measurement SET measurement_concept_id = 3000611 WHERE measurement_concept_id = 0 AND measurement_source_value = 51341\nALTER TABLE measurement SET measurement_concept_id = 3029857 WHERE measurement_concept_id = 0 AND measurement_source_value = 51325\nALTER TABLE measurement SET measurement_concept_id = 3031599 WHERE measurement_concept_id = 0 AND measurement_source_value = 51618\nALTER TABLE measurement SET measurement_concept_id = 3041975 WHERE measurement_concept_id = 0 AND measurement_source_value = 52373\nALTER TABLE measurement SET measurement_concept_id = 3005277 WHERE measurement_concept_id = 0 AND measurement_source_value = 50871\nALTER TABLE measurement SET measurement_concept_i